name = "brainfuck"
version = "0.1.0"
output_dir = "build"

[source.main]
files = ["main.lm"]

[opt.release]
input  = "build/main.ll"
output = "build/main.opt.ll"
level  = "O2"
passes = ["mem2reg", "instcombine", "simplifycfg"]

[link.binary]
linker  = "clang"
inputs  = ["build/main.opt.ll"]
output  = "build/brainfuck"
libs    = ["c"]
