name = "kernel"
version = "0.1.0"
output_dir = "build"
multiboot = true

[source.kernel]
files = ["kernel.lm"]

[link.llc]
linker = "llc"
flags = ["-O2", "-filetype=obj", "-mtriple=x86_64-unknown-linux-gnu", "-relocation-model=static"]
inputs = ["build/kernel.ll"]
output = "build/kernel.o"

[link.as]
linker = "as"
flags = ["--64"]
inputs = ["build/boot.S"]
output = "build/boot.o"

[link.ld]
linker = "ld"
script = "linker.ld"
flags = ["--nmagic"]
inputs = ["build/boot.o", "build/kernel.o"]
output = "build/kernel.elf"

[command.copy-elf]
cmd = "mkdir -p iso/boot && cp build/kernel.elf iso/boot/kernel.elf"

[command.make-iso]
cmd = "grub-mkrescue -o build/kernel.iso iso 2>/dev/null"
