extern "C" {
    fn gtk_init(argc: *i32, argv: **&u8);
    fn gtk_window_new(window_type: i32) -> *void;
    fn gtk_window_set_title(window: *void, title: &u8);
    fn gtk_window_set_default_size(window: *void, width: i32, height: i32);
    fn gtk_window_set_position(window: *void, position: i32);
    fn gtk_container_add(container: *void, widget: *void);
    fn gtk_widget_show_all(window: *void);
    fn gtk_widget_destroy(widget: *void);
    fn gtk_main();
    fn gtk_main_quit();
    fn gtk_box_new(orientation: i32, spacing: i32) -> *void;
    fn gtk_box_pack_start(box: *void, child: *void, expand: i32, fill: i32, padding: u32);
    fn gtk_menu_bar_new() -> *void;
    fn gtk_menu_new() -> *void;
    fn gtk_menu_item_new_with_label(label: &u8) -> *void;
    fn gtk_menu_item_set_submenu(menu_item: *void, submenu: *void);
    fn gtk_menu_shell_append(shell: *void, child: *void);
    fn gtk_separator_menu_item_new() -> *void;
    fn gtk_scrolled_window_new(hadj: *void, vadj: *void) -> *void;
    fn gtk_scrolled_window_set_policy(scrolled: *void, hscroll: i32, vscroll: i32);
    fn gtk_text_view_new() -> *void;
    fn gtk_text_view_get_buffer(text_view: *void) -> *void;
    fn gtk_text_view_set_wrap_mode(text_view: *void, mode: i32);
    fn gtk_text_buffer_get_text(buffer: *void, start: *void, end: *void, include_hidden: i32) -> *void;
    fn gtk_text_buffer_set_text(buffer: *void, text: &u8, len: i32);
    fn gtk_text_buffer_get_start_iter(buffer: *void, iter: *void);
    fn gtk_text_buffer_get_end_iter(buffer: *void, iter: *void);
    fn gtk_dialog_new() -> *void;
    fn gtk_dialog_get_content_area(dialog: *void) -> *void;
    fn gtk_dialog_add_button(dialog: *void, text: &u8, response_id: i32);
    fn gtk_dialog_run(dialog: *void) -> i32;
    fn gtk_window_set_transient_for(window: *void, parent: *void);
    fn gtk_file_chooser_widget_new(action: i32) -> *void;
    fn gtk_file_chooser_get_filename(chooser: *void) -> *void;
    fn gtk_file_chooser_set_current_name(chooser: *void, name: &u8);
    fn gtk_file_chooser_set_do_overwrite_confirmation(chooser: *void, do_confirm: i32);
    fn gtk_widget_get_toplevel(widget: *void) -> *void;
    fn g_signal_connect_data(instance: *void, detailed_signal: &u8, handler: *void, data: *void, destroy_data: *void, connect_flags: i32) -> u64;
    fn g_object_set_data(obj: *void, key: &u8, data: *void);
    fn g_object_get_data(obj: *void, key: &u8) -> *void;
    fn g_free(ptr: *void);
    fn fopen(path: &u8, mode: &u8) -> *void;
    fn fclose(stream: *void) -> i32;
    fn fread(ptr: *void, size: u64, nmemb: u64, stream: *void) -> u64;
    fn fwrite(ptr: *void, size: u64, nmemb: u64, stream: *void) -> u64;
    fn fseek(stream: *void, offset: i64, whence: i32) -> i32;
    fn ftell(stream: *void) -> i64;
    fn malloc(size: u64) -> *void;
    fn free(ptr: *void);
    fn strlen(s: &u8) -> u64;
    fn printf(s: &u8) -> i32;
}
