name = "lumoray"
version = "0.1.0"
output_dir = "build"

[extensions]
dir = "../../build/extensions/example"

[source.main]
files = ["main.lm"]

[opt.release]
input  = "build/main.ll"
output = "build/main.opt.ll"
level = "O2"
passes = ["mem2reg", "instcombine", "simplifycfg", "gvn"]

[link.binary]
linker  = "clang"
inputs  = ["build/main.opt.ll"]
output  = "build/lumoray"
libs    = ["c", "m", "raylib"]
